### ISSUE TITLE
Segfault on missing textcat.cfg

### ISSUE THREAD

**Issue by proycon** [proycon/python-ucto#12]
We output a nice warning that there is no textcat support (missing`textcat.cfg`), but we still segfault after that.

```
20230123:105632:290:mbma-:Initiating morphological analyzer...
20230123:105632:290:mblem-:Initiating lemmatizer...
ucto:NO TEXTCAT SUPPORT DUE TO MISSING textcat.cfg!

Thread 4 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff07fd6c0 (LWP 3236755)]
0x00007ffff7e0aa0f in TextCat::set_debug_stream (s=0x7fffe8000d90, this=0x0) at ../include/ucto/my_textcat.h:55
55	../include/ucto/my_textcat.h: Directory not empty.
(gdb) bt
#0  0x00007ffff7e0aa0f in TextCat::set_debug_stream (s=0x7fffe8000d90, this=0x0) at ../include/ucto/my_textcat.h:55
#1  Tokenizer::TokenizerClass::setErrorLog (this=this@entry=0x7fffe8000f30, os=0x7fffe8000d90) at tokenize.cxx:293
#2  0x00007ffff6765671 in UctoTokenizer::init (this=this@entry=0x7fffe8000b70, config=...) at ucto_tokenizer_mod.cxx:112
#3  0x00007ffff66bec66 in _ZN7FrogAPI7run_apiERKN4TiCC13ConfigurationE._omp_fn.0(void) () at FrogAPI.cxx:923
#4  0x00007ffff1c1b49e in gomp_thread_start () from /home/proycon/tmp/env/lib/python3.10/site-packages/python_frog.libs/libgomp-ef582021.so.1.0.0
#5  0x00007ffff789f8fd in ?? () from /usr/lib/libc.so.6
#6  0x00007ffff7921a60 in ?? () from /usr/lib/libc.so.6
```

(Test was done with python-frog)

I could not reproduce it on a standalone ucto when removing `textcat.cfg` and even the `libexttextcat` dir, so it seems to be something that's triggered only in the binding.

**Comment by proycon** [comment]
Correction: this actually seems to ONLY occur when running from python-frog, not even from python-ucto, transferring issue.
